services:
  db-server:
    container_name: api-nest-database
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api-nest
    ports:
      - 5432:5432